<a href="https://colab.research.google.com/github/sanchit-22/1801155/blob/master/lab1/ass1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PART 1 question 1**



In [ ]:
import numpy as np
A=np.array([0])
B=np.array([1])
C=np.array([5])
for i in range(9):
  A=np.append(A,0)
  B=np.append(B,1)
  C=np.append(C,5)
print(A)
print(B)
print(C)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


**PART 1 question 2**

In [ ]:
import numpy as np
A=np.array([10])
for i in range(11,50):
  if i%2==0:
    A=np.append(A,i)
print(A)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


**PART 1 question 3**

In [ ]:
import numpy as np
x=np.random.random(size=(3,3))
print(x)

[[0.55766034 0.00466092 0.93778963]
 [0.72963517 0.24721152 0.40192418]
 [0.04223058 0.54241835 0.03900684]]


**PART 1 question 4**


In [ ]:
import numpy as np
A=np.random.random(size=(3,3))
print("before loading")
print(A)
f = open("test1_4.txt", "w")
data=str(A)
f.write(data)
f.close()
f = open("test1_4.txt", "r")
print("after loading")
print(f.read()) 

before loading
[[0.41469419 0.04058717 0.62625077]
 [0.23423889 0.06682867 0.64122325]
 [0.32854054 0.79809607 0.13196638]]
after loading
[[0.41469419 0.04058717 0.62625077]
 [0.23423889 0.06682867 0.64122325]
 [0.32854054 0.79809607 0.13196638]]


**PART 2 question 1**

In [ ]:
import pandas as pd
from PIL import Image
import numpy as np
from skimage import io
image = io.imread('https://img.icons8.com/windows/32/000000/online-store.png')
import csv

def csvWriter(fil_name, nparray):
  example = nparray.tolist()
  with open(fil_name+'.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile, delimiter=',')
    writer.writerows(example)
csvWriter("image_matrix", image)



**PART 2 question 2**

In [ ]:
import pandas as pd
def readCSV(CSVfile):
  # function to import data from CSV file w/o last ROW and last COL
  loaded_df = pd.read_csv(CSVfile, skiprows=-1)
  loaded_df = loaded_df.iloc[:, :-1]
  return loaded_df
ReqData = readCSV("image_matrix.csv")

    [0, 0, 0, 0] [0, 0, 0, 0].1  ... [0, 0, 0, 0].29 [0, 0, 0, 0].30
0   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
1   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
2   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
3   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
4   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
5   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
6   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
7   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
8   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
9   [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
10  [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
11  [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
12  [0, 0, 0, 0]   [0, 0, 0, 0]  ...    [0, 0, 0, 0]    [0, 0, 0, 0]
13  [0, 0, 0, 0]   [0, 0, 0, 0]  .

**PART 2 question 3**

In [ ]:
import pandas as pd
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2020-08-23 00:00:00


**PART 3(mini calculator)**

In [ ]:
import numpy as np
while 1:
  x=input("give your date of birth in the format ddmmyyyy")
  x=int(x)
  dob_year=x%10000
  x=int(x/10000)
  dob_month=x%100
  x=int(x/100)
  dob_day=x
  if dob_month==2:
    if dob_year%4==0 and dob_day<=29:
      break
    if dob_year%4!=0 and dob_day<=28:
      break
    else:
      print("error give correct dob")
      continue
  if np.searchsorted(day30,dob_month):
    if dob_day<=30:
      break
    elif dob_day>=31:
      print("error give coorect dob ")
      continue
  if np.searchsorted(day31,dob_month):
    if dob_day<=31:
      break
    elif dob_day>31:
      print("error give correct dob")
      continue
while 1:
  y=input("current date in the format of ddmmyyyy")
  y=int(y)
  date_year=y%10000
  y=int(y/10000)
  date_month=y%100
  y=int(y/100)
  date_day=y
  if date_month==2:
    if date_year%4==0 and date_day<=29:
      break
    if date_year%4!=0 and date_day<=28:
      break
    else:
      print("error give correct date")
      continue
  if np.searchsorted(day30,dob_month):
    if dob_day<=30:
      break
    elif dob_day>=31:
      print("error enter corrent date")
      continue
  if np.searchsorted(day31,dob_month):
    if dob_day<=31:
      break
    elif dob_day>31:
      print("error enter correct date")
      continue

year=date_year-dob_year
month=date_month-dob_month
if month<0 :
  year=year-1
  month=12+month
month=month-1
day31=np.array([0,1,3,5,7,8,10,12])
day30=np.array([0,4,6,9,11])
if np.searchsorted(day30, dob_month):
  day=30-dob_day
if np.searchsorted(day31, dob_month):
  day=31-dob_day
if dob_month==2:
  if dob_year%4==0:
    day=29-dob_day
  else:
    day=28-dob_day
day=day+date_day
if day-31>0:
  day=day-31
  month=month+1
if month<0:
  month=12+month
  year=year-1
print("your age is="+str(year)+ " year "+str(month)+" months "+str(day)+" day")

give your date of birth in the format ddmmyyyy29081994
current date in the format of ddmmyyyy23082020
your age is=25 year 11 months 25 day
